[0m01:13:46.851902 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D25882EB40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D259375D30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D25989CBF0>]}
[0m01:13:46.864902 [debug] [MainThread]: An error was encountered while trying to send an event


============================== 01:13:46.864902 | da571a55-fde5-4b5d-b1c8-12771dd524c6 ==============================
[0m01:13:46.864902 [info ] [MainThread]: Running with dbt=1.9.5
[0m01:13:46.865902 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\yamin\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init dbt_project', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m01:13:46.993901 [debug] [MainThread]: Starter project path: C:\Users\yamin\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m01:13:47.032903 [info ] [MainThread]: 
Your new dbt project "dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m01:13:47.034904 [info ] [MainThread]: Setting up your profile.
[0m01:15:30.572894 [info ] [MainThread]: Profile dbt_project written to C:\Users\yamin\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m01:15:30.574889 [debug] [MainThread]: Command `dbt init` succeeded at 01:15:30.574889 after 104.06 seconds
[0m01:15:30.575889 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2599F8350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D25B2DC410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D259AE1730>]}
[0m01:15:30.576889 [debug] [MainThread]: An error was encountered while trying to send an event
[0m01:15:30.576889 [debug] [MainThread]: Flushing usage events
[0m13:43:30.323993 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210A6BDDCA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210A7537AA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210A6BDF380>]}
[0m13:43:30.343575 [debug] [MainThread]: An error was encountered while trying to send an event


============================== 13:43:30.344585 | dbd3180f-3b92-4b21-87a6-f81a1956edbb ==============================
[0m13:43:30.344585 [info ] [MainThread]: Running with dbt=1.9.5
[0m13:43:30.347584 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\yamin\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:43:30.349584 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\yamin\OneDrive\The-Data-Heist\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:43:30.353596 [debug] [MainThread]: Command `dbt run` failed at 13:43:30.352582 after 0.52 seconds
[0m13:43:30.355592 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210A76819D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210A7537AA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210A4E1DA30>]}
[0m13:43:30.357593 [debug] [MainThread]: An error was encountered while trying to send an event
[0m13:43:30.359595 [debug] [MainThread]: Flushing usage events
